### ISSUE TITLE
No module named bravo.service

### ISSUE THREAD

**Issue by TheLinker** [bravoserver/bravo#128]
On Windows, Python 2.7.1, Twisted 10.2.0

When i run: python twistd.py -y bravo.tac i get:

exceptions.ImportError: No module named bravo.service

Full TraceBack:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 631, in run
    runApp(config)
  File "C:\Python27\lib\site-packages\twisted\scripts\twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 374, in run
    self.application = self.createOrGetApplication()
  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 439, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\application\app.py", line 450, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "C:\Python27\lib\site-packages\twisted\application\service.py", line 400, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "C:\Python27\lib\site-packages\twisted\persisted\sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "bravo.tac", line 1, in <module>
    from bravo.service import application
exceptions.ImportError: No module named bravo.service

Failed to load application: No module named bravo.service

**Comment by MostAwesomeDude** [comment]
Bet this is yet another JSON-related problem. To figure out which package is _actually_ missing, open a Python shell and do:

```
>>> import bravo.service
```

**Comment by mattbasta** [comment]
I was able to avoid this error by running:

```
python setup.py install
```

from the bravo root directory.

**Comment by TheLinker** [comment]
fixed, used mattbasta fix.

maybe README.rst on git root should be revised:

"Important: Bravo's installation process is currently broken. Until this notice is removed, please don't install, just run directly from the git checkout. It's easier and runs just as well."
