### ISSUE TITLE
Unhandled error using the mouse wheel

### ISSUE THREAD

**Issue by barsch** [bravoserver/bravo#160]
Got this error with the current trunk, new world and default bravo.ini.

2011-03-18 17:25:42+0100 [BravoProtocol,0,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "D:\Python\bravo\27\win32\lib\site-packages\twisted-10.2.0-py2.7-win32.egg\twisted\python\log.py", line 84, in callWithLogger
            return callWithContext({"system": lp}, func, _args, *_kw)
          File "D:\Python\bravo\27\win32\lib\site-packages\twisted-10.2.0-py2.7-win32.egg\twisted\python\log.py", line 69, in callWithContext
            return context.call({ILogContext: newCtx}, func, _args, *_kw)
          File "D:\Python\bravo\27\win32\lib\site-packages\twisted-10.2.0-py2.7-win32.egg\twisted\python\context.py", line 59, in callWithContext
            return self.currentContext().callWithContext(ctx, func, _args, *_kw)
          File "D:\Python\bravo\27\win32\lib\site-packages\twisted-10.2.0-py2.7-win32.egg\twisted\python\context.py", line 37, in callWithContext
            return func(_args,_*kw)
        --- <exception caught here> ---
          File "D:\Python\bravo\27\win32\lib\site-packages\twisted-10.2.0-py2.7-win32.egg\twisted\internet\selectreactor.py", line 146, in _doReadOrWrite
            why = getattr(selectable, method)()
          File "D:\Python\bravo\27\win32\lib\site-packages\twisted-10.2.0-py2.7-win32.egg\twisted\internet\tcp.py", line 460, in doRead
            return self.protocol.dataReceived(data)
          File "d:\workspace\bravo\bravo\protocols\beta.py", line 256, in dataReceived
            self.handlers[header](payload)
          File "d:\workspace\bravo\bravo\protocols\beta.py", line 705, in equip
            secondary=secondary
          File "d:\workspace\bravo\bravo\packets.py", line 529, in make_packet
            payload = packets[header].build(container)
          File "D:\Python\bravo\27\win32\lib\site-packages\construct-2.04-py2.7.egg\construct\core.py", line 136, in build
            self.build_stream(obj, stream)
          File "D:\Python\bravo\27\win32\lib\site-packages\construct-2.04-py2.7.egg\construct\core.py", line 140, in build_stream
            self._build(obj, stream, AttrDict())
          File "D:\Python\bravo\27\win32\lib\site-packages\construct-2.04-py2.7.egg\construct\core.py", line 572, in _build
            sc._build(subobj, stream, context)
          File "D:\Python\bravo\27\win32\lib\site-packages\construct-2.04-py2.7.egg\construct\core.py", line 270, in _build
            raise FieldError(ex)
        construct.core.FieldError: integer out of range for 'H' format code

**Comment by MostAwesomeDude** [comment]
Does fe5e1e8d22ba15926251418827f807e9d3151ce0 fix it?

**Comment by barsch** [comment]
yes - seems to work
