### ISSUE TITLE
Malformed File Error

### ISSUE THREAD

**Issue by dbdii407** [bravoserver/bravo#173]
I was able to connect the first time. After messing around on the server, I disconnected and now have this.

```
2011-03-28 20:17:12-0400 [bravo.factories.beta.BravoFactory] Starting connection for IPv4Address(TCP, '127.0.0.1', 48106)
2011-03-28 20:17:12-0400 [bravo.factories.beta.BravoFactory] Registering client hooks...
2011-03-28 20:17:12-0400 [bravo.factories.beta.BravoFactory] Discovering <InterfaceClass bravo.ibravo.IBuildHook>...
...
2011-03-28 20:17:12-0400 [BravoProtocol,0,127.0.0.1] Authenticating client, protocol version 9
2011-03-28 20:17:12-0400 [BravoProtocol,0,127.0.0.1] Unhandled error in Deferred:
2011-03-28 20:17:12-0400 [BravoProtocol,0,127.0.0.1] Unhandled Error

Traceback (most recent call last):
  File "/home/dbdii407/Applications/bravo/bravo/protocols/beta.py", line 257, in dataReceived
    self.handlers[header](payload)
  File "/home/dbdii407/Applications/bravo/bravo/protocols/beta.py", line 554, in login
    d.addCallback(lambda *args, **kwargs: self.authenticated())
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 297, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 286, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 542, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/dbdii407/Applications/bravo/bravo/protocols/beta.py", line 554, in <lambda>
    d.addCallback(lambda *args, **kwargs: self.authenticated())
  File "/home/dbdii407/Applications/bravo/bravo/protocols/beta.py", line 427, in authenticated
    self.player = self.factory.world.load_player(self.username)
  File "/home/dbdii407/Applications/bravo/bravo/world.py", line 353, in load_player
    self.serializer.load_player(player)
  File "/home/dbdii407/Applications/bravo/bravo/plugins/serializers.py", line 451, in load_player
    tag = self._read_tag(fp)
  File "/home/dbdii407/Applications/bravo/bravo/plugins/serializers.py", line 134, in _read_tag
    return NBTFile(fileobj=fp.open("r"))
  File "/home/dbdii407/Applications/bravo/bravo/nbt.py", line 290, in __init__
    self.parse_file()
  File "/home/dbdii407/Applications/bravo/bravo/nbt.py", line 313, in parse_file
    raise MalformedFileError("Partial File Parse: file possibly truncated.")
bravo.nbt.MalformedFileError: Partial File Parse: file possibly truncated.
```

**Comment by squiddy** [comment]
Looks like the player dat file wasn't written entirely. Can you reproduce this error?

**Comment by dbdii407** [comment]
I remember using /give and the items were stuck in the wall at some points. Usually if you mess around a bit you can reproduce the error.

**Comment by squiddy** [comment]
Okay. I've been messing around with bravo for a while now, and I never had an error related to NBT parsing like this. There is not a lot of code for reading/writing player files, so somehow writing to that file must have been interrupted. Could you upload that player file somewhere?

**Comment by dbdii407** [comment]
Type "/give wood 1024". You will recieve a struct error: "struct.error: byte format requires -128 <= number <= 127" and will be disconnected.

**Comment by MostAwesomeDude** [comment]
That is completely unrelated, although a2a9898bfa147b0df154973aa2c832f357debf27 fixes that issue, so thanks for mentioning it. :3

Maybe we need to use set_content() or other strong tools for atomic writes.

**Comment by dbdii407** [comment]
No problem, thank you for the fix!

**Comment by MostAwesomeDude** [comment]
Closing due to lack of feedback. set_content() should probably be investigated at some point, although we now have the correct exception handlers in place for allowing failed writes and reads.
