### ISSUE TITLE
Cannot run benchmarks

### ISSUE THREAD

**Issue by progval** [bravoserver/bravo#233]
Hello,

I am getting this, when running benchmarks (from the Git head):

```
progval@ProgVal-Andromede-Debian:~/src/bravo$ ./run_benchmarks.py 
/home/progval/src/bravo/exocet/_exocet.py:785: RuntimeWarning: Parent module 'twisted.internet' not found while handling absolute import
  return _originalImport(name, globals, *a, **kw)
/home/progval/src/bravo/exocet/_exocet.py:785: RuntimeWarning: Parent module 'xml.sax' not found while handling absolute import
  return _originalImport(name, globals, *a, **kw)
Running benchmarks in chunks...
chunk_baseline: Average 0.036821, min 0.029802, max 0.146151, stddev 0.116269
Traceback (most recent call last):
  File "./run_benchmarks.py", line 63, in <module>
    main()
  File "./run_benchmarks.py", line 50, in main
    name, l = benchmark()
  File "benchmarks/chunks.py", line 39, in seq
    l = [sequential_seeded(i, plugin) for i in xrange(25)]
  File "benchmarks/chunks.py", line 12, in wrapped
    f(*args, **kwargs)
  File "benchmarks/chunks.py", line 23, in sequential_seeded
    p.populate(chunk, i)
  File "/home/progval/src/bravo/bravo/plugins/generators.py", line 343, in populate
    height = octaves2(magx, magz, 6)
  File "/home/progval/src/bravo/bravo/simplex.py", line 262, in octaves2
    sigma += simplex2(x * divisor, y * divisor) / divisor
  File "/home/progval/src/bravo/bravo/simplex.py", line 96, in simplex2
    raise Exception("The gradient field is unseeded!")
Exception: The gradient field is unseeded!
```

Regards,
ProgVal

**Comment by MostAwesomeDude** [comment]
Benchmarks are somewhat broken and there's no good reason to unbreak them. Just noting that this is not a high-priority issue.

**Comment by mjevans** [comment]
Sadly it is no longer just benchmarks, I partly blame 9cfd0752333fb9a4a12509ac2dc07c845ef9cef8 ; but I suspect exocet is the real cause.  It appears to be interfering with libraries including other parts of themselves.

**Comment by MostAwesomeDude** [comment]
Closing this. Benchmarks will not be unbroken until codespeed is usable.
