### ISSUE TITLE
Ampoule race condition

### ISSUE THREAD

**Issue by gtaylor** [bravoserver/bravo#236]
Getting the following with ampoule enabled on Mac OS 10.6, MacPorts Python 2.6, Twisted 11.0, latest Bravo from master. Disabling ampoule fixes the issue, but figured I'd point this out:

(bravo)snagglepants ~/Documents/workspace/bravo: twistd -ny bravo.tac
/Users/gtaylor/Documents/workspace/bravo/exocet/_exocet.py:785: RuntimeWarning: Parent module 'twisted.internet' not found while handling absolute import
  return _originalImport(name, globals, _a, *_kw)
/Users/gtaylor/Documents/workspace/bravo/exocet/_exocet.py:785: RuntimeWarning: Parent module 'xml.sax' not found while handling absolute import
  return _originalImport(name, globals, _a, *_kw)
2011-05-01 21:20:06-0400 [-] Log opened.
2011-05-01 21:20:06-0400 [-] twistd 11.0.0 (/Users/gtaylor/.virtualenvs/bravo/bin/python 2.6.6) starting up.
2011-05-01 21:20:06-0400 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2011-05-01 21:20:06-0400 [-] bravo.amp.ConsoleRPCFactory starting on 25600
2011-05-01 21:20:06-0400 [-] Starting factory <bravo.amp.ConsoleRPCFactory instance at 0x101ecdb90>
2011-05-01 21:20:06-0400 [-] bravo.factories.beta.BravoFactory starting on 25565
2011-05-01 21:20:06-0400 [-] Starting factory <bravo.factories.beta.BravoFactory instance at 0x101ecdc20>
2011-05-01 21:20:06-0400 [-] Initializing factory for world 'example'...
2011-05-01 21:20:06-0400 [-] Discovering <InterfaceClass bravo.ibravo.ISerializerFactory>...
2011-05-01 21:20:06-0400 [-](^^) Plugin: beta
2011-05-01 21:20:06-0400 [-](^^) Plugin: alpha
2011-05-01 21:20:06-0400 [-](^^) Plugin: beta
2011-05-01 21:20:06-0400 [-] Loaded level data!
2011-05-01 21:20:06-0400 [-] World started on file:///Users/gtaylor/Documents/workspace/bravo/world, using serializer beta
2011-05-01 21:20:06-0400 [-] Using Ampoule: True
2011-05-01 21:20:06-0400 [-] Setting cache size to 3...
2011-05-01 21:20:06-0400 [-] Starting timekeeping...
2011-05-01 21:20:06-0400 [-] Discovering <InterfaceClass bravo.ibravo.ISeason>...
2011-05-01 21:20:06-0400 [-](^^) Plugin: spring
2011-05-01 21:20:06-0400 [-](^^) Plugin: winter
2011-05-01 21:20:06-0400 [-] Discovering <InterfaceClass bravo.ibravo.IAuthenticator>...
2011-05-01 21:20:06-0400 [-](^^) Plugin: password
2011-05-01 21:20:06-0400 [-](^^) Plugin: online
2011-05-01 21:20:06-0400 [-](^^) Plugin: offline
2011-05-01 21:20:06-0400 [-] Using authenticator offline
2011-05-01 21:20:06-0400 [-] Discovering <InterfaceClass bravo.ibravo.ITerrainGenerator>...
2011-05-01 21:20:07-0400 [-](^^) Plugin: float
2011-05-01 21:20:07-0400 [-](^^) Plugin: complex
2011-05-01 21:20:07-0400 [-](^^) Plugin: safety
2011-05-01 21:20:07-0400 [-](^^) Plugin: saplings
2011-05-01 21:20:07-0400 [-](^^) Plugin: caves
2011-05-01 21:20:07-0400 [-](^^) Plugin: erosion
2011-05-01 21:20:07-0400 [-](^^) Plugin: cliffs
2011-05-01 21:20:07-0400 [-](^^) Plugin: simplex
2011-05-01 21:20:07-0400 [-](^^) Plugin: ore
2011-05-01 21:20:07-0400 [-](^^) Plugin: beaches
2011-05-01 21:20:07-0400 [-](^^) Plugin: boring
2011-05-01 21:20:07-0400 [-](^^) Plugin: watertable
2011-05-01 21:20:07-0400 [-](^^) Plugin: grass
2011-05-01 21:20:07-0400 [-] Using generators boring, simplex, erosion, grass, caves, cliffs, safety
2011-05-01 21:20:07-0400 [-] Discovering <InterfaceClass bravo.ibravo.IAutomaton>...
2011-05-01 21:20:07-0400 [-](^^) Plugin: water
2011-05-01 21:20:07-0400 [-](^^) Plugin: lava
2011-05-01 21:20:07-0400 [-] Using automatons water, lava
2011-05-01 21:20:07-0400 [-] Factory successfully initialized for world 'example'!
2011-05-01 21:20:07-0400 [-] twisted.web.server.Site starting on 8080
2011-05-01 21:20:07-0400 [-] Starting factory <twisted.web.server.Site instance at 0x101e4fb90>
2011-05-01 21:20:07-0400 [-] Subprocess 0 started.
2011-05-01 21:20:07-0400 [-] AMP connection established (HOST:('no host',) PEER:('subprocess',))
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-] Log opened.
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-] /Users/gtaylor/.virtualenvs/bravo/lib/python2.6/site-packages/ampoule/main.py:4: exceptions.DeprecationWarning: the sets module is deprecated
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-] Slave connection established (HOST:<twisted.internet._posixstdio.PipeAddress object at 0x1020af710> PEER:<twisted.internet._posixstdio.PipeAddress object at 0x1020af6d0>)
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-] Discovering <InterfaceClass bravo.ibravo.ITerrainGenerator>...
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: float
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: complex
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: safety
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: saplings
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: caves
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: erosion
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: cliffs
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: simplex
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: ore
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: beaches
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: boring
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: watertable
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-](^^) Plugin: grass
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-] exocet/_exocet.py:785: exceptions.RuntimeWarning: Parent module 'twisted.internet' not found while handling absolute import
2011-05-01 21:20:07-0400 [-] FROM 0: 2011-05-01 21:20:07-0400 [-] exocet/_exocet.py:785: exceptions.RuntimeWarning: Parent module 'xml.sax' not found while handling absolute import
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory] Starting connection for IPv4Address(TCP, '127.0.0.1', 50551)
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory] Registering client hooks...
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory] Discovering <InterfaceClass bravo.ibravo.IBuildHook>...
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: build_snow
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: build
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: tile
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: bravo_snow
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: alpha_sand_gravel
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: painting
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: redstone
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: tracks
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory] Discovering <InterfaceClass bravo.ibravo.IDigHook>...
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: bravo_snow
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: alpha_sand_gravel
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: torch
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: give
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: replace
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: alpha_snow
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: water
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: redstone
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: lava
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: tracks
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory] Discovering <InterfaceClass bravo.ibravo.ISignHook>...
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory] Discovering <InterfaceClass bravo.ibravo.IUseHook>...
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory](^^) Plugin: painting
2011-05-01 21:20:11-0400 [bravo.factories.beta.BravoFactory] Registered entity <bravo.protocols.beta.BravoProtocol instance at 0x102221dd0>
2011-05-01 21:20:11-0400 [BravoProtocol,0,127.0.0.1] Authenticating client, protocol version 11
2011-05-01 21:20:14-0400 [-] Unhandled error in Deferred:
2011-05-01 21:20:14-0400 [-] Unhandled Error
    Traceback (most recent call last):
      File "/Users/gtaylor/.virtualenvs/bravo/lib/python2.6/site-packages/twisted/internet/defer.py", line 1076, in gotResult
        _inlineCallbacks(r, g, deferred)
      File "/Users/gtaylor/.virtualenvs/bravo/lib/python2.6/site-packages/twisted/internet/defer.py", line 1063, in _inlineCallbacks
        deferred.callback(e.value)
      File "/Users/gtaylor/.virtualenvs/bravo/lib/python2.6/site-packages/twisted/internet/defer.py", line 361, in callback
        self._startRunCallbacks(result)
      File "/Users/gtaylor/.virtualenvs/bravo/lib/python2.6/site-packages/twisted/internet/defer.py", line 455, in _startRunCallbacks
        self._runCallbacks()
    --- <exception caught here> ---
      File "/Users/gtaylor/.virtualenvs/bravo/lib/python2.6/site-packages/twisted/internet/defer.py", line 542, in _runCallbacks
        current.result = callback(current.result, _args, *_kw)
      File "/Users/gtaylor/Documents/workspace/bravo/bravo/protocols/beta.py", line 942, in send_chunk
        packet = make_packet("prechunk", x=chunk.x, z=chunk.z, enabled=1)
    exceptions.AttributeError: 'NoneType' object has no attribute 'x'

**Comment by MostAwesomeDude** [comment]
Marking for 1.5. This is a known race which I keep forgetting to fix; hopefully this issue will get me to be more attentive.

**Comment by hikari-no-yume** [comment]
This usually happens for me if I create a new world with ampoule on. If I create it with ampoule off, then restart with ampoule on, I don't see it. Although there's obviously a chance it will happen at some point.
