### ISSUE TITLE
Ladder build hook does not work

### ISSUE THREAD

**Issue by progval** [bravoserver/bravo#242]
Hello,

When adding "ladder" to the build_hooks, I get this error:

```
    Traceback (most recent call last):
      File "/usr/lib/python2.6/dist-packages/twisted/python/log.py", line 69, in callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 118, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
      File "/usr/lib/python2.6/dist-packages/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
        why = getattr(selectable, method)()
    --- <exception caught here> ---
      File "/usr/lib/python2.6/dist-packages/twisted/internet/tcp.py", line 942, in doRead
        protocol = self.factory.buildProtocol(self._buildAddr(addr))
      File "/home/progval/src/bravo.new/bravo/factories/beta.py", line 119, in buildProtocol
        p = self.protocol(self.name)
      File "/home/progval/src/bravo.new/bravo/protocols/beta.py", line 431, in __init__
        self.build_hooks = retrieve_sorted_plugins(IBuildHook, names)
      File "/home/progval/src/bravo.new/bravo/plugin.py", line 248, in retrieve_sorted_plugins
        l = retrieve_named_plugins(interface, names)
      File "/home/progval/src/bravo.new/bravo/plugin.py", line 241, in retrieve_named_plugins
        (e.args[0], interface))
    bravo.plugin.PluginException: Couldn't find plugin ladder for interface <InterfaceClass bravo.ibravo.IBuildHook>!
```

Regards,
ProgVal

**Comment by squiddy** [comment]
Docs are wrong. There used to be a `ladder` build plugin, but orientation is now done by the generic build plugin with the help of metadata in bravo.blocks.
