### ISSUE TITLE
Client can't connect

### ISSUE THREAD

**Issue by progval** [bravoserver/bravo#270]
Hello,

When connecting to Bravo, I get this, and the client is disconnected:

```

    Traceback (most recent call last):
      File "/usr/lib/python2.6/dist-packages/twisted/python/log.py", line 69, in callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 118, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
      File "/usr/lib/python2.6/dist-packages/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
        why = getattr(selectable, method)()
    --- <exception caught here> ---
      File "/usr/lib/python2.6/dist-packages/twisted/internet/tcp.py", line 942, in doRead
        protocol = self.factory.buildProtocol(self._buildAddr(addr))
      File "/home/progval/src/bravo/bravo/factories/beta.py", line 120, in buildProtocol
        p = self.protocol(self.name)
      File "/home/progval/src/bravo/bravo/protocols/beta.py", line 437, in __init__
        self.dig_hooks = retrieve_sorted_plugins(IDigHook, names)
      File "/home/progval/src/bravo/bravo/plugin.py", line 248, in retrieve_sorted_plugins
        l = retrieve_named_plugins(interface, names)
      File "/home/progval/src/bravo/bravo/plugin.py", line 241, in retrieve_named_plugins
        (e.args[0], interface))
    bravo.plugin.PluginException: Couldn't find plugin replace for interface <InterfaceClass bravo.ibravo.IDigHook>!
```

Regards,
ProgVal

**Comment by squiddy** [comment]
You probably need to update your `bravo.ini`. The `Replace` plugin was removed some time ago, so you just need to remove it from your `dig_hooks`.

**Comment by alucas** [comment]
I think we need to create a FAQ with some common problems. And perhaps catch this exception.

**Comment by justinnoah** [comment]
heero78, the exception is caught:
bravo.plugin.PluginException: Couldn't find plugin replace for interface <InterfaceClass bravo.ibravo.IDigHook>!

and this needs to stay as being fatal. Bad names for plugins shouldn't happen.

**Comment by EntityReborn** [comment]
Should not this issue be closed?
