### ISSUE TITLE
./run_benchmarks.sh fails

### ISSUE THREAD

**Issue by justinnoah** [bravoserver/bravo#283]
./run_benchmarks.py 
Running benchmarks in chunks...
chunk_baseline: Average 0.037012, min 0.030994, max 0.090122, stddev 0.074939
Traceback (most recent call last):
  File "./run_benchmarks.py", line 63, in <module>
    main()
  File "./run_benchmarks.py", line 50, in main
    name, l = benchmark()
  File "benchmarks/chunks.py", line 39, in seq
    l = [sequential_seeded(i, plugin) for i in xrange(25)]
  File "benchmarks/chunks.py", line 12, in wrapped
    f(_args, *_kwargs)
  File "benchmarks/chunks.py", line 23, in sequential_seeded
    p.populate(chunk, i)
  File "/home/chaos/projects/bravo/bravo/plugins/generators.py", line 344, in populate
    height = octaves2(magx, magz, 6)
  File "/home/chaos/projects/bravo/bravo/simplex.py", line 262, in octaves2
    sigma += simplex2(x \* divisor, y \* divisor) / divisor
  File "/home/chaos/projects/bravo/bravo/simplex.py", line 96, in simplex2
    raise Exception("The gradient field is unseeded!")
Exception: The gradient field is unseeded!

**Comment by justinnoah** [comment]
I just noticed this is a dupe. Sorry about that.
