### ISSUE TITLE
Jack-o-lanterns aren't placeable

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#392]

**Comment by MostAwesomeDude** [comment]
```
Traceback (most recent call last):
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 203, in doRead
    return self._dataReceived(data)
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/simpsoco/bravo/bravo/beta/protocol.py", line 349, in dataReceived
    self.handlers[header](payload)
  File "/home/simpsoco/bravo/bravo/beta/protocol.py", line 1138, in equip
    secondary=secondary
  File "/home/simpsoco/bravo/bravo/beta/packets.py", line 847, in make_packet
    payload = packets[header].build(container)
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/construct/core.py", line 206, in build
    self.build_stream(obj, stream)
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/construct/core.py", line 214, in build_stream
    self._build(obj, stream, Container())
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/construct/core.py", line 664, in _build
    sc._build(subobj, stream, context)
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/construct/core.py", line 266, in _build
    self.subcon._build(obj, stream, context)
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/construct/core.py", line 664, in _build
    sc._build(subobj, stream, context)
  File "/home/simpsoco/local/local/lib/python2.7/site-packages/construct/core.py", line 361, in _build
    raise FieldError(ex)
construct.core.FieldError: 'h' format requires -32768 <= number <= 32767
```
