### ISSUE TITLE
pip install bravo

### ISSUE THREAD

**Issue by tom-spalding** [bravoserver/bravo#451]
`pip install Bravo` doesn't download the `requirements.txt` file, just an fyi.

```
sudo pip install Bravo
Downloading/unpacking Bravo
  Downloading Bravo-2.0.tar.gz (173Kb): 173Kb downloaded
  Running setup.py egg_info for package Bravo
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/root/build/Bravo/setup.py", line 13, in <module>
        install_requires=open("requirements.txt").read().split("\n"),
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/build/Bravo/setup.py", line 13, in <module>

    install_requires=open("requirements.txt").read().split("\n"),

IOError: [Errno 2] No such file or directory: 'requirements.txt'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /root/.pip/pip.log
```

**Comment by edunham** [comment]
oh Pip. Thank you for letting us know; it seems it's time for me to go learn about packaging :)

**Comment by tom-spalding** [comment]
:)
