### ISSUE TITLE
Cannot get it working event with the 1.6.4 client

### ISSUE THREAD

**Issue by Th4nat0s** [bravoserver/bravo#453]
Upon connection, the client is stuck on "loading world"  

2014-09-11 07:13:47+0200 [bravo.beta.factory.BravoFactory] Starting connection for IPv4Address(TCP, '192.168.XX.XX', 49219)
2014-09-11 07:13:47+0200 [bravo.beta.factory.BravoFactory] Registered entity <bravo.beta.protocol.BravoProtocol object at 0xb395d0c>
2014-09-11 07:13:47+0200 [bravo.beta.factory.BravoFactory] Registering client hooks...
2014-09-11 07:13:47+0200 [bravo.beta.factory.BravoFactory] Registering policies...
2014-09-11 07:13:47+0200 [bravo.beta.factory.BravoFactory] Registered client plugin hooks!
2014-09-11 07:13:47+0200 [BravoProtocol,0,192.168.XX.XX] Poll data: 'N\x00\x0c\x001\x009\x002\x00.\x001\x006\x008\x00.\x001\x00.\x001\x003\x00\x00c\xd
d'
2014-09-11 07:13:47+0200 [BravoProtocol,0,192.168.XX.XX] Error: u'\xa71\x0078\x00Bravo 2.0\x00BravoServer\x000\x001000000'
2014-09-11 07:13:50+0200 [bravo.beta.factory.BravoFactory] Starting connection for IPv4Address(TCP, '192.168.XX.XX', 49221)
2014-09-11 07:13:50+0200 [bravo.beta.factory.BravoFactory] Registered entity <bravo.beta.protocol.BravoProtocol object at 0xb3975ac>
2014-09-11 07:13:50+0200 [bravo.beta.factory.BravoFactory] Registering client hooks...
2014-09-11 07:13:50+0200 [bravo.beta.factory.BravoFactory] Registering policies...
2014-09-11 07:13:50+0200 [bravo.beta.factory.BravoFactory] Registered client plugin hooks!
2014-09-11 07:13:50+0200 [BravoProtocol,1,192.168.XX.XX Handshaking with client, protocol version 78
2014-09-11 07:13:50+0200 [BravoProtocol,1,192.168.XX.XX] Couldn't load player u'R3psak'
2014-09-11 07:13:50+0200 [BravoProtocol,1,192.168.XX.XX] Chat: §2R3psak§f is joining the game...
2014-09-11 07:13:50+0200 [BravoProtocol,1,192.168.XX.XX] Unhandled error in Deferred:
2014-09-11 07:13:50+0200 [BravoProtocol,1,192.168.XX.XX] Unhandled Error
                Traceback (most recent call last):
          File "/home/thanatos/code/bravo/bravo/beta/protocol.py", line 391, in dataReceived
            d = maybeDeferred(self.handlers[header], payload)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 134, in maybeDeferred
            result = f(_args, *_kw)
          File "/home/thanatos/code/bravo/bravo/beta/protocol.py", line 164, in handshake
            self.authenticated()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1187, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1045, in _inlineCallbacks
            result = g.send(result)
          File "/home/thanatos/code/bravo/bravo/beta/protocol.py", line 804, in authenticated
            packet += self.inventory.save_to_packet()
          File "/home/thanatos/code/bravo/bravo/inventory/windows.py", line 112, in save_to_packet
            packet = make_packet("inventory", wid=self.wid, length=len(l), items=l)
          File "/home/thanatos/code/bravo/bravo/beta/packets.py", line 1060, in make_packet
            payload = packets[header].build(container)
          File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 212, in build
            self.build_stream(obj, stream)
          File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 219, in build_stream
            self._build(obj, stream, Container())
          File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 691, in _build
            sc._build(subobj, stream, context)
          File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 449, in _build
            if len(obj) != count:
        exceptions.TypeError: object of type 'instancemethod' has no len()

2014-09-11 07:13:51+0200 [BravoProtocol,1,192.168.XX.XX] "Didn't handle parseable packet 0xfa!"
2014-09-11 07:13:51+0200 [BravoProtocol,1,192.168.XX.XX] Container({'data': 'vanilla', 'channel': u'MC|Brand'})

**Comment by edunham** [comment]
Sorry for the extremely long delay on reply here; Bravo's 2.0 release worked with 1.4.x clients and Minecraft's development has outpaced Bravo's since then.

**Comment by Th4nat0s** [comment]
Ok :)
