### ISSUE TITLE
Running 'twistd -n bravo' crashes with dump

### ISSUE THREAD

**Issue by ghost** [bravoserver/bravo#63]
UPDATE: Thie ticket link below identifies the same issue and also a fix which appears to work. There is still some output at the start, but I think the server is running now.

https://github.com/MostAwesomeDude/bravo/issues#issue/47

Thank you.

---

Hi there,

Here is the output from my console. I'm running Mnadriva Linux. I'm new to Python stuff but I figured out that installing Bravo was done via the 'python setup.py bravo' command. Once that successfully completed, I tried 'twistd -n bravo' and got this:

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/application/app.py", line 606, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/usage.py", line 226, in parseOptions
    for (cmd, short, parser, doc) in self.subCommands:
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/application/app.py", line 616, in subCommands
    for plug in plugins:
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugin.py", line 199, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugin.py", line 178, in getCache
    dropinPath.setContent(pickle.dumps(dropinDotCache))
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/filepath.py", line 765, in setContent
    f = sib.open('w')
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/filepath.py", line 515, in open
    return self.create()
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/filepath.py", line 791, in create
    fdint = os.open(self.path, _CREATE_FLAGS)
exceptions.OSError: [Errno 13] Permission denied: '/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugins/VAbo_omj04IXjDUIdropin.cache.new'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/application/app.py", line 606, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/usage.py", line 226, in parseOptions
    for (cmd, short, parser, doc) in self.subCommands:
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/application/app.py", line 616, in subCommands
    for plug in plugins:
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugin.py", line 199, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugin.py", line 164, in getCache
    provider = pluginModule.load()
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/reflect.py", line 464, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/twisted/plugins/bravod.py", line 7, in <module>
    from bravo.service import service
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/service.py", line 6, in <module>
    from bravo.factory import BetaFactory
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/factory.py", line 9, in <module>
    from bravo.entity import Pickup, Player
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/entity.py", line 4, in <module>
    from bravo.inventory import Equipment, ChestStorage
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/inventory.py", line 9, in <module>
    from bravo.serialize import InventorySerializer
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/serialize.py", line 6, in <module>
    from bravo.serializers.json import *
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/serializers/json.py", line 11, in <module>
    raise ImportError("Couldn't find a JSON library!")
exceptions.ImportError: Couldn't find a JSON library!
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/usage.py", line 413, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/usage.py", line 449, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/application/app.py", line 616, in subCommands
    for plug in plugins:
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugin.py", line 199, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugin.py", line 178, in getCache
    dropinPath.setContent(pickle.dumps(dropinDotCache))
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/filepath.py", line 765, in setContent
    f = sib.open('w')
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/filepath.py", line 515, in open
    return self.create()
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/filepath.py", line 791, in create
    fdint = os.open(self.path, _CREATE_FLAGS)
exceptions.OSError: [Errno 13] Permission denied: '/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugins/pzAsQhzcTOpPti1Fdropin.cache.new'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/usage.py", line 413, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/usage.py", line 449, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/application/app.py", line 616, in subCommands
    for plug in plugins:
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugin.py", line 199, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugin.py", line 164, in getCache
    provider = pluginModule.load()
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/reflect.py", line 464, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/twisted/plugins/bravod.py", line 7, in <module>
    from bravo.service import service
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/service.py", line 6, in <module>
    from bravo.factory import BetaFactory
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/factory.py", line 9, in <module>
    from bravo.entity import Pickup, Player
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/entity.py", line 4, in <module>
    from bravo.inventory import Equipment, ChestStorage
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/inventory.py", line 9, in <module>
    from bravo.serialize import InventorySerializer
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/serialize.py", line 6, in <module>
    from bravo.serializers.json import *
  File "/home/rocky1138/Downloads/MostAwesomeDude-bravo-d23cc92/bravo/serializers/json.py", line 11, in <module>
    raise ImportError("Couldn't find a JSON library!")
exceptions.ImportError: Couldn't find a JSON library!

I'd love to get this thing up and running as this project looks really sweet. Can you offer any advice to help? Thx.

**Comment by ghost** [comment]
So you discovered that your issue was a duplicate, but opted not to close it? Please do so.

**Comment by ghost** [comment]
Sorry -- I'm brand new to Github. Was just trying to help out :)

**Comment by MostAwesomeDude** [comment]
As mentioned in the other bug, there's some issues with the way JSON support is discovered. It might not have been the best choice for a default. :3

Anyway, lemme know if you have other issues!
