### ISSUE TITLE
Disconnect on selection outside of inventory

### ISSUE THREAD

**Issue by MostAwesomeDude** [bravoserver/bravo#74]
```
    Traceback (most recent call last):
      File "/usr/lib/python2.6/dist-packages/twisted/python/log.py", line 84, in callWithLogger
        return callWithContext({"system": lp}, func, *args, **kw)
      File "/usr/lib/python2.6/dist-packages/twisted/python/log.py", line 69, in callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 59, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 37, in callWithContext
        return func(*args,**kw)
    --- <exception caught here> ---
      File "/usr/lib/python2.6/dist-packages/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
        why = getattr(selectable, method)()
      File "/usr/lib/python2.6/dist-packages/twisted/internet/tcp.py", line 460, in doRead
        return self.protocol.dataReceived(data)
      File "/home/corbin/bravo/bravo/protocol.py", line 423, in dataReceived
        self.handlers[header](payload)
      File "/home/corbin/bravo/bravo/protocol.py", line 328, in waction
        selected = i.select(container.slot, bool(container.button))
      File "/home/corbin/bravo/bravo/inventory.py", line 197, in select
        l, index = self.container_for_slot(slot)
    exceptions.TypeError: 'NoneType' object is not iterable
```

**Comment by MostAwesomeDude** [comment]
Fixed.
