### ISSUE TITLE
Requested traceback.

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#9]
Traceback (most recent call last):
  File "./main.py", line 8, in <module>
    reactor.run()
  File "/usr/lib64/python2.6/site-packages/twisted/internet/base.py", line 1128, in run
    self.mainLoop()
  File "/usr/lib64/python2.6/site-packages/twisted/internet/base.py", line 1140, in mainLoop
    self.doIteration(t)
  File "/usr/lib64/python2.6/site-packages/twisted/internet/selectreactor.py", line 140, in doSelect
    _logrun(selectable, _drdw, selectable, method, dict)
--- <exception caught here> ---
  File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "/usr/lib64/python2.6/site-packages/twisted/python/context.py", line 37, in callWithContext
    return func(_args,_*kw)
  File "/usr/lib64/python2.6/site-packages/twisted/internet/selectreactor.py", line 156, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, method=="doRead")
  File "/usr/lib64/python2.6/site-packages/twisted/internet/posixbase.py", line 190, in _disconnectSelectable
    selectable.readConnectionLost(f)
  File "/usr/lib64/python2.6/site-packages/twisted/internet/tcp.py", line 509, in readConnectionLost
    self.connectionLost(reason)
  File "/usr/lib64/python2.6/site-packages/twisted/internet/tcp.py", line 520, in connectionLost
    protocol.connectionLost(reason)
  File "/home/Actown/Games/mcserver/beta/protocol.py", line 357, in connectionLost
    if self.username in self.factory.players:
exceptions.AttributeError: AlphaProtocol instance has no attribute 'username'

**Comment by MostAwesomeDude** [comment]
Fixed by e5e1bd1a6b0892e3c7bd502ab1ad886ace1b3d97.
